import time
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
driver=webdriver.Chrome()
driver.get("https://www.flipkart.com/")
driver.maximize_window()
driver.implicitly_wait(10)
driver.find_element(By.XPATH,"//input[@name='q']").send_keys("iphone")
driver.find_element(By.XPATH,"//button[@type='submit']").submit()
# driver.execute_script("arguments[0].click();", login)
# driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div/div/div[2]/div/form/div[1]/input").send_keys("srividya994@gmail.com")
# time.sleep(10)
driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div/div/div[2]/div/form/div[3]/button").click()
time.sleep(10)
driver.close()
# a=driver.find_elements(By.XPATH,"/html/body/div[2]/div/div/div/div/div[2]/div/div/form/div/div")
# a[1].send_keys(input("enter 1st number"))
# driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div/div/div[2]/div/div/form/button").click()
# #email=driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div/div/div[2]/div/form/div[1]/input")
# newuser=driver.find_element(By.PARTIAL_LINK_TEXT,"New to Flipkart? Create an account")
# time.sleep(10)
# act=ActionChains(driver)
# act.move_to_element(newuser).click().perform()
# time.sleep(10)
# cont=driver.find_element(By.XPATH,"//*[@id='container']/div/div[1]/div[1]/div[2]/div[2]/form/div/button")
# a=driver.execute_script("arguments[0].click();",cont)
# driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div/div/div[2]/div/form/div[3]/a").click()
# driver.save_screenshot("C:/Selenium webdriver/flipkart.png")
# driver.close()
